import {chromium} from 'playwright';import assert from 'node:assert/strict';import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.TEST_URL||'http://127.0.0.1:5178/babylon-lite-garden-chat/';
await mkdir('test-results',{recursive:true});const browser=await chromium.launch({channel:'chromium',headless:true,args:['--enable-unsafe-webgpu','--ignore-gpu-blocklist']});const errors=[];
async function open(context){const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await p.bringToFront();await p.goto(url);try{await p.waitForFunction(()=>document.querySelector('#garden').dataset.ready==='true',null,{timeout:45000});}catch(e){console.log('Startup failure',await p.locator('#garden').getAttribute('data-stage'),await p.locator('#overlay').innerText(),errors);await p.screenshot({path:'test-results/failure.png'});throw e;}await p.waitForFunction(()=>window.gardenDiagnostics?.().status==='connected',{timeout:45000});return p;}
const self=async p=>p.evaluate(()=>{const s=gardenDiagnostics();return s.players.find(x=>x.id===s.sessionId);});
async function say(p,text){await p.locator('#message').fill(text);await p.locator('#message').press('Enter');await p.waitForTimeout(850);}
try{
 const c1=await browser.newContext({viewport:{width:1440,height:1000}}),c2=await browser.newContext({viewport:{width:1440,height:1000}});const a=await open(c1);let b=await open(c2);
 assert.equal(await a.evaluate(()=>gardenDiagnostics().roomId),await b.evaluate(()=>gardenDiagnostics().roomId));
 const start=await self(a),peer=await self(b);await a.locator('#garden').focus();await a.keyboard.down('d');await a.waitForTimeout(1200);await a.keyboard.up('d');await a.waitForTimeout(250);const moved=await self(a),bumped=await self(b);assert.ok(moved.x>start.x+1,'WASD moves');assert.ok(bumped.x>peer.x+.4,'collision pushes peer');assert.ok(Math.hypot(moved.x-bumped.x,moved.z-bumped.z)>.98,'no overlap');
 const beforeUp=await self(a);await a.keyboard.down('ArrowUp');await a.waitForTimeout(400);await a.keyboard.up('ArrowUp');await a.waitForTimeout(200);assert.ok((await self(a)).z<beforeUp.z-.5,'arrow movement');
 await a.locator('#pause').click();const paused=await self(a);await a.keyboard.down('d');await a.waitForTimeout(350);await a.keyboard.up('d');assert.ok(Math.abs((await self(a)).x-paused.x)<.15,'pause stops');await a.locator('#pause').click();
 await a.locator('#message').focus();const typing=await self(a);await a.keyboard.type('wasd');await a.waitForTimeout(350);assert.ok(Math.abs((await self(a)).x-typing.x)<.15,'typing stops movement');
 await say(a,'Hello from this little patch of green 🌿');await b.waitForFunction(()=>gardenDiagnostics().chats.some(m=>m.text.includes('little patch')));
 await say(b,'Hi Peach! A lovely place to slow down.');await say(a,'<b>Kind words grow here.</b>');assert.equal(await b.locator('#messages b').count(),0,'chat is literal text');
 await a.screenshot({path:'test-results/desktop.png'});
 const firstDeparted=(await self(b)).id;await b.locator("#leave").click();await a.waitForFunction(id=>!gardenDiagnostics().players.some(p=>p.id===id),firstDeparted);await c2.close();
 const c3=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const mobile=await open(c3);assert.ok(await mobile.locator('#messages').innerText().then(t=>t.includes('little patch')),'late history');
 assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight),true,'mobile fits');
 const touchBefore=await self(mobile);const rect=await mobile.locator('[data-key="ArrowDown"]').boundingBox();const cdp=await c3.newCDPSession(mobile);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width/2,y:rect.y+rect.height/2}]});await mobile.waitForTimeout(500);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mobile.waitForTimeout(200);assert.ok((await self(mobile)).z>touchBefore.z+.5,'touch movement');await mobile.screenshot({path:'test-results/mobile.png'});b=mobile;
 for(let i=0;i<11;i++)await say(b,'Garden note '+(i+1)+': happy to share this peaceful afternoon with you.');
 await a.locator('#messages').evaluate(el=>el.scrollTop=0);await say(b,'A new note while you read earlier messages.');assert.ok(await a.locator('#messages').evaluate(el=>el.scrollTop<10),'preserve scroll');assert.ok(await a.locator('#latest').isVisible());await a.locator('#latest').click();assert.ok(await a.locator('#messages').evaluate(el=>el.scrollHeight-el.scrollTop-el.clientHeight<35));
 const departed=(await self(b)).id;await b.locator('#leave').click();await a.waitForFunction(id=>!gardenDiagnostics().players.some(p=>p.id===id),departed);await b.locator('#leave').click();await b.waitForFunction(()=>gardenDiagnostics().status==='connected');assert.notEqual((await self(b)).id,departed,'fresh rejoin');
 await a.locator('#garden').focus();await a.keyboard.down('s');await a.waitForTimeout(150);await a.evaluate(()=>window.dispatchEvent(new Event('blur')));await a.waitForTimeout(200);const blur=await self(a);await a.waitForTimeout(400);assert.ok(Math.abs((await self(a)).z-blur.z)<.1,'blur releases input');await a.keyboard.up('s');
 const unsupported=await browser.newContext();await unsupported.addInitScript(()=>Object.defineProperty(navigator,'gpu',{get:()=>undefined}));const up=await unsupported.newPage();await up.goto(url);await up.waitForFunction(()=>document.querySelector('#overlay-message').textContent.includes('WebGPU'));await unsupported.close();
 assert.deepEqual(errors,[],'runtime errors');await writeFile('test-results/verification.json',JSON.stringify({url,passed:true,checks:['WebGPU desktop','two clients','WASD and arrows','collision','pause','typing isolation','chat relay','safe HTML','late history','mobile layout','emulated touch','history scroll','hot drop and fresh rejoin','blur release','unsupported GPU'],errors},null,2));console.log('PASS: desktop/mobile WebGPU, two-client movement/collision/chat, late join, hot drop, rejoin, input safety and history.');
}finally{await browser.close();}



